version: '2'

services:
  web:
    image: nginx:${NGINX_VERSION}
    env_file: .env
    ports:
      - "${HTTP_BINDED_PORT}:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - code-network

  php:
    image: spalacios/php7.3-fpm-prestashop:1.0
    env_file: .env
    volumes:
      - ./:/var/www/html
      - ./.docker/php/conf/php.ini:/usr/local/etc/php/php.ini
    expose:
      - 9000
    networks:
      - code-network

  mysql:
    image: mysql:${MYSQL_VERSION}
    env_file: .env
    ports:
      - "${DATABASE_BINDED_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./.docker/volume/mysql:/var/lib/mysql
    networks:
      - code-network

  mailhog:
    image: mailhog/mailhog
    env_file: .env
    hostname: "mailhog"
    ports:
      - 1025
      - "${MAILHOG_BINDED_PORT}:8025"
    networks:
      - code-network

networks:
  code-network:
    driver: bridge